travis:
  secure:
    BINSTAR_TOKEN: SDmGHTyzP0/+kMyuztdcDkj+sHQbqLYHt+5ioJqAA2Y6qo4Z1xtrPPBiLbTHv1ZzlRGyzNaWuPqxbp3tH91zJfplFWFXcAbfP+S9SU/7+6CWGySfGMQS399+cWSWMdPhbaaw6T6yFKlsMZaQ2nr5lonGIH+pjjxQ8NJH7f4o4AwcS96kQVqkuodTvcykPzVhgO0aen5EZu91tb64rps40K0SHtnLdi+kJmS8S+GsEwxIHj8wJYBYEBEYN/eAxHNzAAnMM/u5YUW4hANKPEoBFFIXgRsdYy0PPGmuSwikQaprkyqoLDDoiFJ7fvclQFzpRSFjrfK68PvuimD9audzy3JqIwkLEUI3WXhfCDyfi22lLPKHvRj0ASxO8mdNyX8cBxdbMvkn/MD7G7BFGv/qAoavAnJjMpFsu9svetFnSwOWRdvUFgh8ak6B43Rx0VqotFK7l4muGtis0FeRQleNV/uDRXn+JsJ7OMBzsMU+TQvY9VjOzHWWWANhhtRjUGj69Ty3xdwFbJ8t60whew/xSpIW/T9ZV2P8y9VxbfqhN226mwjqSP/6ruvUoeOetPSrMjoKvVDCDakwWqws4pYBuJ2VCI12yzgwYRYyriWgDp1o1Rr8aE+7JYvlP3oiNmuHePDBCVOdnB4efq/eG5BexAAJSxVX+ff1vmtVCu7FlxM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
